apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fp4vnpvv4-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fp4vnpvv4-python 
  name: fp4vnpvv4-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fp4vnpvv4-python 
